//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Core/Input/MvA main control.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MvAInputSystem: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MvAInputSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MvA main control"",
    ""maps"": [
        {
            ""name"": ""MainControl"",
            ""id"": ""a08a6e53-9c01-4fab-99ac-698f3ab846df"",
            ""actions"": [
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""59f9b5cd-4d21-4bf6-9eb2-41be8697c455"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0f80cdaa-2004-4365-b0cb-9309fa75d471"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MainControl
        m_MainControl = asset.FindActionMap("MainControl", throwIfNotFound: true);
        m_MainControl_MousePosition = m_MainControl.FindAction("MousePosition", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MainControl
    private readonly InputActionMap m_MainControl;
    private List<IMainControlActions> m_MainControlActionsCallbackInterfaces = new List<IMainControlActions>();
    private readonly InputAction m_MainControl_MousePosition;
    public struct MainControlActions
    {
        private @MvAInputSystem m_Wrapper;
        public MainControlActions(@MvAInputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @MousePosition => m_Wrapper.m_MainControl_MousePosition;
        public InputActionMap Get() { return m_Wrapper.m_MainControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainControlActions set) { return set.Get(); }
        public void AddCallbacks(IMainControlActions instance)
        {
            if (instance == null || m_Wrapper.m_MainControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainControlActionsCallbackInterfaces.Add(instance);
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
        }

        private void UnregisterCallbacks(IMainControlActions instance)
        {
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
        }

        public void RemoveCallbacks(IMainControlActions instance)
        {
            if (m_Wrapper.m_MainControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainControlActions instance)
        {
            foreach (var item in m_Wrapper.m_MainControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainControlActions @MainControl => new MainControlActions(this);
    public interface IMainControlActions
    {
        void OnMousePosition(InputAction.CallbackContext context);
    }
}
